### ISSUE TITLE
Suggestions for the "packaging"

### ISSUE THREAD

**Issue by gvegayon** [pachamaltese/oec#1]
Hey pacha,

I'm checking out oec and looks very neat! Although, as a R-package developer, I do have some suggestions for future releases:

1. Try to avoid using "Depends". Instead use "Imports". This should make the package load faster, remove messages about loading other packages and further make everything safer since it will require making calls using the namespace instead, eg. if I use the Moran.I function in the ape package, using Imports requires me to do type `ape::Moran.I` in every call of the function.

2. Try not to mess around with the user's dirs. Instead of copying files to the current dir, try copying (and cleaning after yourself) files to the temp dir. Using the `demo` dir makes it [nicer](https://github.com/gvegayon/rgexf/tree/master/demo)

3. In the `getdata` function I would include a `@returns` field. Furthermore, from what I see it might be good to define a class (S3) so that you can interact with R's generic functions print-plot-summary, etc.

4. Since the API does not require using a key, you can implement tests using the `testthat` package easily. It would be nice =).

Best,

G

**Comment by pachamaltese** [comment]
Hi George 

Thanks a lot. This is a good way to start the day !!

You are completely right. In my own case, I did follow this quote from Donald E. Knuth "We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil."

I agree with most points but about point 3 I have to say that one of the ideas was to provide the user with a copy of the data for the case he/she needs to make a presentation in a place where the wifi is not so good or when he/she needs the data in csv to prepare charts by using Excel or Google Drive.

As soon as D3Plus 2.0 stable is released I'm gonna add these suggestions for a new version of this package.

Best regards,
帕夏
